import type { NextPage } from 'next'
import Head from 'next/head'
import { EthereumClient, w3mConnectors, w3mProvider } from '@web3modal/ethereum'
import { Web3Modal } from '@web3modal/react'

import {configureChains, createClient, WagmiConfig} from 'wagmi'
import { bscTestnet, fantomTestnet } from 'wagmi/chains'

import HomePage from "../components/HomePage";

const chains = [bscTestnet, fantomTestnet]
const projectId: string = '77690b7f1ebcea841c98780513dce7a0'

const { provider } = configureChains(chains, [w3mProvider({ projectId })])
const wagmiClient = createClient({
    autoConnect: true,
    connectors: w3mConnectors({ projectId, version: 1, chains }),
    provider
})
const ethereumClient:EthereumClient = new EthereumClient(wagmiClient, chains)

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <WagmiConfig client={wagmiClient}>
            <HomePage/>
        </WagmiConfig>

        <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
    </div>
  )
}

export default Home
